language: ruby
rvm:
  - 1.9.3

before_install:
  - gem update --system
  - rvm @default,@global do gem uninstall -ax bundler
  - gem install bundler --pre

before_script:
  - "rake db:reset"

script: rake test && rake
